name: Azure Static Web Apps CI/CD - Testing

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job - Testing
    env:  # Setting environment variables specific to the testing environment
      REACT_APP_GOOGLE_CLIENT_ID: '838062661118-ktim79hu56fe6ot7c8cj3spjf81oiec4.apps.googleusercontent.com'  # Change this value to your testing environment's specific client ID
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TESTING }}  # Ensure you have this secret set in your GitHub repo
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "/"  # Adjust if your testing environment has a different app location
          api_location: "api"  # Adjust if your testing environment has a different API location or if not applicable
          output_location: "build"  # Adjust if your testing environment builds to a different output directory
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job - Testing
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TESTING }}  # Use the same testing environment token
          action: "close"